<?php
declare(strict_types=1);

if (!function_exists('etds_doctor_score_build')) {
  function etds_doctor_score_build(array $context, array $validation): array {
    $extractionSummary = is_array($context['extraction'] ?? null) ? $context['extraction'] : [];
    $validationSummary = is_array($validation['summary'] ?? null) ? $validation['summary'] : [];
    $deductees = is_array($context['deductees'] ?? null) ? $context['deductees'] : [];
    $challans = is_array($context['challans'] ?? null) ? $context['challans'] : [];
    $salary = is_array($context['salary'] ?? null) ? $context['salary'] : [];
    $payments = is_array($context['payments'] ?? null) ? $context['payments'] : [];

    $extractionScore = (int) ($extractionSummary['overall_confidence'] ?? 0);
    $validationScore = (int) ($validationSummary['quality_score'] ?? 0);
    $totalRecords = count($deductees) + count($challans) + count($salary) + count($payments);
    $populatedGroups = 0;
    foreach ([$deductees, $challans, $salary, $payments] as $group) {
      if (count($group) > 0) {
        $populatedGroups++;
      }
    }
    $completenessScore = $totalRecords === 0 ? 0 : min(100, (int) round(($populatedGroups / 4) * 100));

    $critical = (int) ($validationSummary['critical'] ?? 0);
    $high = (int) ($validationSummary['high'] ?? 0);
    $medium = (int) ($validationSummary['medium'] ?? 0);
    $low = (int) ($validationSummary['low'] ?? 0);
    $information = (int) ($validationSummary['information'] ?? 0);
    $consistencyScore = max(0, 100 - ($critical * 18) - ($high * 12) - ($medium * 6) - ($low * 3) - $information);

    $overall = (int) round(($extractionScore * 0.20) + ($validationScore * 0.40) + ($completenessScore * 0.20) + ($consistencyScore * 0.20));

    return [
      'extraction_score' => max(0, min(100, $extractionScore)),
      'validation_score' => max(0, min(100, $validationScore)),
      'completeness_score' => max(0, min(100, $completenessScore)),
      'consistency_score' => max(0, min(100, $consistencyScore)),
      'overall_data_health_score' => max(0, min(100, $overall)),
      'methodology' => [
        'extraction_score' => 'Uses the overall extraction confidence from extraction.json.',
        'validation_score' => 'Uses the quality score generated by the Validation Rules Engine.',
        'completeness_score' => 'Measures whether deductee, challan, salary, and payment datasets are populated for the case.',
        'consistency_score' => 'Applies weighted deductions based on open Critical, High, Medium, Low, and Information findings.',
        'overall_data_health_score' => 'Weighted blend: Extraction 20%, Validation 40%, Completeness 20%, Consistency 20%.',
      ],
    ];
  }
}
